base_url = "alonsomoya.com"
title = "Hola"
description = "ğŸ’» âœˆï¸ ğŸš´ ğŸ‚ ğŸ¥˜"

# The default language; used in feeds.
default_language = "en"

# The site theme to use.
theme = "hallo"

compile_sass = false
highlight_code = true
highlight_theme = "boron"

build_search_index = false
generate_feed = true
feed_filename = "index.xml"

############################
[extra]
greeting = "Â¡Hola!"

iam = "I am"

links = [
    { title = "E-Mail", url = "mailto:jose@alonsomoya", iconset = "fas", icon = "envelope" },
    { title = "Linkedin", url = "https://www.linkedin.com/in/jjavieralonso/", icon = "linkedin" },
    { title = "GitHub", url = "https://github.com/alonsomoya/", icon = "github" },
#    { title = "Twitter", url = "https://twitter.com/JJAlonso91", icon = "twitter" },
    { title = "Instagram", url = "https://www.instagram.com/jose.alo/", icon = "instagram" },
    { title = "CV", iconset="fa", url = "https://raw.githubusercontent.com/pant03/cv/master/CV_JoseAlonso.pdf", icon = "file-pdf" }
]

[extra.author]
name = "Jose"

[extra.theme]
background = "#6FCDBD"
foreground = "#FFF"
hover = "#333"

[author]
name = "Jose Alonso"
homepage = "https://alonsomoya.com"

[original]
author =  "Jan Baudisch/Emiel Hollander"
homepage = "https://janbaudisch.dev / https://themes.gohugo.io/theme/hallo-hugo/"
repo = "https://github.com/EmielH/hallo-hugo"

